export const ACTIONS = {

    USER_LOGIN:{
        USER_LOGGING:"LOGGING[USER]",
        USER_LOGGEDIN:"LOGGEDIN[USER]",
        USER_LOGIN_FAILED: "LOGINFAIL[USER]"
    },
    CLIENTS_DATA:{
        CLIENTS_GETTING:"GETTING[CLIENTS]",
        CLIENTS_FAILED:"FAILED[CLIENTS]",
        CLIENTS_GOT:"GOT[CLIENTS]"
    },
    FILTERED_USERS:{
        FILTERED_USERS_GETTING:"GETTING[FILTERED_USERS]",
        FILTERED_USERS_FAILED:"FAILED[FILTERED_USERS]",
        FILTERED_USERS_GOT:"GOT[FILTERED_USERS]",
        FILTERED_USERS_CLEAR:"CLEAR[FILTERED_USERS]",
    },
    DEPARTMENTS:{
        DEPARTMENTS_GETTING:"GETTING[DEPARTMENTS]",
        DEPARTMENTS_FAILED:"FAILED[DEPARTMENTS]",
        DEPARTMENTS_GOT:"GOT[DEPARTMENTS]",
    },
    SPORTS_CAT:{
        SPORTS_CAT_GETTING:"GETTING[SPORTS_CAT]",
        SPORTS_CAT_FAILED:"FAILED[SPORTS_CAT]",
        SPORTS_CAT_GOT:"GOT[SPORTS_CAT]",
    },
    GROUPS:{
        GROUPS_GETTING:"GETTING[GROUPS]",
        GROUPS_FAILED:"FAILED[GROUPS]",
        GROUPS_GOT:"GOT[GROUPS]",
    },
    USERS_DROPDOWN:{
        USERS_DROPDOWN_GETTING:"GETTING[USERS_DROPDOWN]",
        USERS_DROPDOWN_GOT:"GOT[USERS_DROPDOWN]",
        USERS_DROPDOWN_FAILED:"FAILED[USERS_DROPDOWN]",
    },

    GROUP_CREATE:{
        GROUP_CREATING:"CREATING[GROUP_CREATE]",
        GROUP_CREATED:"CREATED[GROUP_CREATE]",
        GROUP_CREATION_FAILED:"CREATION_FAILED[GROUP_CREATE]",
    },

    RESPONSE:{
        NEW_GROUP:{
            NEW_GROUP_SUCCESS:"SUCCESS[NEW_GROUP]",
            NEW_GROUP_FAILED:"FAILED[NEW_GROUP]",
            NEW_GROUP_CREATING:"CREATING[NEW_GROUP]",
            NEW_GROUP_CLEAR:"CLEAR[NEW_GROUP]",
        },
        NEW_CHALLENGE:{
            NEW_CHALLENGE_SUCCESS:"SUCCESS[NEW_CHALLENGE]",
            NEW_CHALLENGE_FAILED:"FAILED[NEW_CHALLENGE]",
            NEW_CHALLENGE_CREATING:"CREATING[NEW_CHALLENGE]",
            NEW_CHALLENGE_CLEAR:"CLEAR[NEW_CHALLENGE]",
        },
        NEW_NOTIFICATION:{
            NEW_NOTIFICATION_SUCCESS:"SUCCESS[NEW_NOTIFICATION]",
            NEW_NOTIFICATION_FAILED:"FAILED[NEW_NOTIFICATION]",
            NEW_NOTIFICATION_CREATING:"CREATING[NEW_NOTIFICATION]",
            NEW_NOTIFICATION_CLEAR:"CLEAR[NEW_NOTIFICATION]",
        },
    },

    USERS:{
        USERS_GETTING:"GETTING[USERS]",
        USERS_FAILED:"FAILED[USERS]",
        USERS_GOT:"GOT[USERS]",
    },

    DASHBOARD:{
        DASHBOARD_GYM_GETTING:"GETTING[DASHBOARD_GYM]",
        DASHBOARD_GYM_GOT:"GOT[DASHBOARD_GYM]",
        DASHBOARD_GYM_FAILED:"FAILED[DASHBOARD_GYM]",
        
        DASHBOARD_NOTIFICATION_GETTING:"GETTING[DASHBOARD_NOTIFICATION]",
        DASHBOARD_NOTIFICATION_GOT:"GOT[DASHBOARD_NOTIFICATION]",
        DASHBOARD_NOTIFICATION_FAILED:"FAILED[DASHBOARD_NOTIFICATION]",
        
        DASHBOARD_EVENT_PARTICIPANTS_GETTING:"GETTING[DASHBOARD_EVENT_PARTICIPANTS]",
        DASHBOARD_EVENT_PARTICIPANTS_GOT:"GOT[DASHBOARD_EVENT_PARTICIPANTS]",
        DASHBOARD_EVENT_PARTICIPANTS_FAILED:"FAILED[DASHBOARD_EVENT_PARTICIPANTS]",

        DASHBOARD_UPCOMING_CHALLENGE_GETTING:"GETTING[DASHBOARD_UPCOMING_CHALLENGE]",
        DASHBOARD_UPCOMING_CHALLENGE_GOT:"GOT[DASHBOARD_UPCOMING_CHALLENGE]",
        DASHBOARD_UPCOMING_CHALLENGE_FAILED:"FAILED[DASHBOARD_UPCOMING_CHALLENGE]",

        DASHBOARD_CURRENT_CHALLENGE_GETTING:"GETTING[DASHBOARD_CURRENT_CHALLENGE_FAILED]",
        DASHBOARD_CURRENT_CHALLENGE_GOT:"GOT[DASHBOARD_CURRENT_CHALLENGE_FAILED]",
        DASHBOARD_CURRENT_CHALLENGE_FAILED:"FAILED[DASHBOARD_CURRENT_CHALLENGE_FAILED]",

    },

    GYM_CHECKINS:{
        GYM_CHECKINS_GETTING:"GETTING[GYM_CHECKINS]",
        GYM_CHECKINS_FAILED:"FAILED[GYM_CHECKINS]",
        GYM_CHECKINS_GOT:"GOT[GYM_CHECKINS]",
    },

    REPORT:{
        GYM_CHECKINS:{
            GYM_CHECKINS_BY_ORG:{
                GYM_CHECKINS_BY_ORG_GETTING:"GETTING[GYM_CHECKINS_BY_ORG]",
                GYM_CHECKINS_BY_ORG_GOT:"GOT[GYM_CHECKINS_BY_ORG]",
                GYM_CHECKINS_BY_ORG_FAILED:"FAILED[GYM_CHECKINS_BY_ORG]",
            },
            GYM_CHECKINS_BY_GROUPS:{
                GYM_CHECKINS_BY_GROUPS_GETTING:"GETTING[GYM_CHECKINS_BY_GROUPS]",
                GYM_CHECKINS_BY_GROUPS_GOT:"GOT[GYM_CHECKINS_BY_GROUPS]",
                GYM_CHECKINS_BY_GROUPS_FAILED:"FAILED[GYM_CHECKINS_BY_GROUPS]",
            }
        },
        ORG_PARTICIPATION:{
            EVENT_INVITES:{
                EVENT_INVITES_BY_ORG_GETTING:"GETTING[EVENT_INVITES_BY_ORG]",
                EVENT_INVITES_BY_ORG_GOT:"GOT[EVENT_INVITES_BY_ORG]",
                EVENT_INVITES_BY_ORG_FAILED:"FAILED[EVENT_INVITES_BY_ORG]",
            },
            EVENTS_BY_ORG:{
                EVENTS_BY_ORG_GETTING:"GETTING[EVENTS_BY_ORG]",
                EVENTS_BY_ORG_GOT:"GOT[EVENTS_BY_ORG]",
                EVENTS_BY_ORG_FAILED:"FAILED[EVENTS_BY_ORG]",
            },
            EVENTS_BY_GROUPS:{
                EVENTS_BY_GROUPS_GETTING:"GETTING[EVENTS_BY_GROUPS]",
                EVENTS_BY_GROUPS_GOT:"GOT[EVENTS_BY_GROUPS]",
                EVENTS_BY_GROUPS_FAILED:"FAILED[EVENTS_BY_GROUPS]",
            }
        },
        SPORTS:{

            SPORTS_PLAYERS_GRAPH_BY_SPORT:{
                SPORTS_PLAYERS_GRAPH_BY_SPORT_GETTING:"GETTING[SPORTS_PLAYERS_GRAPH_BY_SPORT]",
                SPORTS_PLAYERS_GRAPH_BY_SPORT_GOT:"GOT[SPORTS_PLAYERS_GRAPH_BY_SPORT]",
                SPORTS_PLAYERS_GRAPH_BY_SPORT_FAILED:"FAILED[SPORTS_PLAYERS_GRAPH_BY_SPORT]",
            }
        },


        
    },

    CHALLENGE_DETAILS:{
        CHALLENGE_DETAILS_GETTING:"GETTING[CHALLENGE_DETAILS]",
        CHALLENGE_DETAILS_GOT:"GOT[CHALLENGE_DETAILS]",
        CHALLENGE_DETAILS_FAILED:"FAILED[CHALLENGE_DETAILS]",
    }

}